### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request failed with status code 422

### ISSUE THREAD

**Issue by mwkcoding** [patoroco/doorkeeper#7]
How do I fix this? I followed the example and input the name of the firewall.

**Comment by patoroco** [comment]
Hi, could you give me some more context? Maybe you're setting the wrong secrets?

**Comment by basmilius** [comment]
Hi. I also have this issue, I know for sure that my DO key and the name of my firewall are valid.  It shows the following error:
```
(node:3776) UnhandledPromiseRejectionWarning: Error: Request failed with status code 422
    at createError (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:10643:15)
    at settle (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:7688:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:8788:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by basmilius** [comment]
So I got the "adding ip" part working, i cannot have outbound rules in my firewall and then it works. But there's something else now, my droplets and tags are getting removed from the firewall. The request body when updating a firewall should contain `droplet_ids` and `tags`.

**Comment by patoroco** [comment]
Could you prepare a test and send a PR with a sample, @basmilius? It could help more people.

Thanks!

**Comment by yringler** [comment]
> So I got the "adding ip" part working, i cannot have outbound rules in my firewall and then it works. But there's something else now, my droplets and tags are getting removed from the firewall. The request body when updating a firewall should contain `droplet_ids` and `tags`.

Thank you @basmilius ! I tried removing outbound rules, and I stopped seeing the 42 error.
And likewise, I saw that my droplet was removed from the firewall.

**Comment by yringler** [comment]
I added a PR #13.
This resolves the droplets being removed; I didn't look into supporting outbound rules.

_Update_
Still no errors after adding back outbound rules

**Comment by SpaceBaar** [comment]
There is this problem of having ICMP protocol in your firewall rules, you can't use "0" or "all" when trying to update the rules.
You have to remove the ports properties for ICMP rules.

See the following thread on [digitalocean community](https://www.digitalocean.com/community/questions/api-error-you-must-specify-a-positive-value-for-ports)

I can confirm that after deleting the ports property while preparing outbound rules for ICMP works properly. But it would fail otherwise in the current state with the same error of 422 Unprocessable entity.

**Comment by patoroco** [comment]
@SpaceBaar thanks for the comment! Do you have any suggestions about how to deal with this? A PR would be well received by doorkeeper’s users :)
